// Generated by IcedCoffeeScript 1.6.2a
(function() {
  var $, iced, search, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  $ = require('jquery');

  search = function(keyword) {
    var base, json, url, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    base = "https://app.rakuten.co.jp/services/api/IchibaItem/Search/20130424?format=json&applicationId=1084425069581237387";
    url = "" + base + "&keyword=" + keyword + "&callback=?";
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "examples/iced-coffee-script-output/rakuten_search2.coffee",
        funcname: "search"
      });
      $.getJSON(url, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return json = arguments[0];
          };
        })(),
        lineno: 4
      }));
      __iced_deferrals._fulfill();
    })(function() {
      return console.log(json.results);
    });
  };

  search("iPod");

}).call(this);
